services:
    lockey:
        build: 
            context: .
            dockerfile: Dockerfile
        image: lockey:1.0
        container_name: lockey
        depends_on:
            - lockey-db 
        environment:
            - "DJANGO_PRODUCTION=True"
            - "DJANGO_BASE_URL=http://localhost:8080/"
            - "DJANGO_SECRET_KEY=-e^)23vce!)!)gl2xo##3mebev!%27i%2nl#pml1qh2(@t(u(u"
            - "DJANGO_ADMIN_USER=admin"
            - "DJANGO_ADMIN_PASS=admin"
            - "DB_HOST=lockey-db"
            - "DB_PORT=3306"
            - "DB_NAME=lockeydb"
            - "DB_USER=admin"
            - "DB_PASS=admin"
        volumes:
            - type: bind
              source: ./media
              target: /usr/src/app/media/

    lockey-front:
        image: lockey-front:1.0
        container_name: lockey-front
        depends_on:
            - lockey 
        environment:
            - "API_BASE_URL=http://localhost:8080/api/v1/"
        
    lockey-proxy:
        image: nginx:1.27.2
        container_name: lockey-proxy
        depends_on:
            - lockey
            - lockey-front
        volumes:
            - type: bind
              source: nginx.conf
              target: /etc/nginx/conf.d/default.conf
            - type: bind
              source: ./media
              target: /usr/share/nginx/html/media
        ports:
            - target: 80
              published: 8080

    lockey-db:
        image: mysql:9.1.0
        container_name: lockey-db
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=lockeydb"
            - "MYSQL_USER=admin"
            - "MYSQL_PASSWORD=admin"
        cap_add:
            - SYS_NICE
        volumes:
            - type: volume
              source: mysql_data
              target: /var/lib/mysql

volumes:
    mysql_data:
        external: true
