services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        image: lockey:1.0
        depends_on:
            - mysql 
        environment:
            - "DJANGO_PRODUCTION=True"
            - "DJANGO_ADMIN_USER=admin"
            - "DJANGO_ADMIN_PASS=admin"
            - "DJANGO_SECRET_KEY=-e^)23vce!)!)gl2xo##3mebev!%27i%2nl#pml1qh2(@t(u(u"
            - "DB_HOST=mysql"
            - "DB_PORT=3306"
            - "DB_NAME=lockeydb"
            - "DB_USER=admin"
            - "DB_PASS=admin"
        volumes:
            - type: volume
              source: lockey_data
              target: /usr/src/app/media/

    mysql:
        image: mysql:9.1.0
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=lockeydb"
            - "MYSQL_USER=admin"
            - "MYSQL_PASSWORD=admin"
        cap_add:
            - SYS_NICE
        volumes:
            - type: volume
              source: mysql_data
              target: /var/lib/mysql

volumes:
    mysql_data:
        external: true
    lockey_data:
        external: true