[tool.autopep8]
max_line_length = 120
ignore = ""
in-place = true
recursive = true
aggressive = 2

[tool.flake8]
exclude = [
    "__pycache__/",
    ".git/",
    ".venv/",
    "venv*/",
    "*/migrations/",
    "settings.py"
    ]
max_line_length = 120
statistics = true
count = true
