[tool.autopep8]
max_line_length = 120
ignore = ""
in-place = true
recursive = true
aggressive = 2

[tool.flake8]
exclude = [
    "__pycache__/",
    ".git/",
    ".venv/",
    "venv*/",
    "*/migrations/",
    "settings.py"
    ]
max_line_length = 120
statistics = true
count = true

[tool.pre-commit]
[[tool.pre-commit.repos]]
repo = "https://github.com/hhatto/autopep8"
rev = "2.3.1"
[[tool.pre-commit.repos.hooks]]
id = "autopep8"

[[tool.pre-commit.repos]]
repo = "https://github.com/pycqa/flake8"
rev = "7.1.1"
[[tool.pre-commit.repos.hooks]]
id = "flake8"
