"""
Django settings for lockey project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / "../.env")

BASE_URL = env.str("DJANGO_BASE_URL", default="http://localhost:8080/")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("DJANGO_SECRET_KEY", default="changeme")

PRODUCTION = env.bool("DJANGO_PRODUCTION", default=False)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False) or not PRODUCTION

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])

CORS_ALLOWED_ORIGINS = env.list("DJANGO_CORS_ALLOWED_ORIGINS", default=["http://localhost:9000"])

PASSWORD_ALLOWED_CHARS = env.str("PASSWORD_ALLOWED_CHARS", default="QWERTYUPASDFHKLZXCVB23456789!?@#$%^&*()")
PASSWORD_LENGHT = env.int("PASSWORD_LENGHT", default=12)

LOCKEY_DISABLE_WHITELIST = env.bool("LOCKEY_DISABLE_WHITELIST", default=False) or not PRODUCTION

# Application definition
INSTALLED_APPS = [
    "django_extensions",  # extra admin commands (devenv)
    "django.contrib.sessions",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django_filters",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "drf_standardized_errors",
    "corsheaders",
    "apps.whitelist",
    "apps.permission",
    "apps.group",
    "apps.user",
    "apps.folder",
    "apps.credential",
]

AUTH_USER_MODEL = "user.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "middleware.security.AuditLogMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.security.AccessWhitelistMiddleware",
]

ROOT_URLCONF = "lockey.urls"


WSGI_APPLICATION = "lockey.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASE_PRD = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": env.str("DB_NAME", default="lockeydb"),
    "USER": env.str("DB_USER", default="admin"),
    "PASSWORD": env.str("DB_PASS", default="admin"),
    "HOST": env.str("DB_HOST", default="localhost"),
    "PORT": env.str("DB_PORT", default="3306"),
}
DATABASE_DEV = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR / "sqlite3.db",
}
DATABASES = {"default": DATABASE_PRD if PRODUCTION else DATABASE_DEV}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "validator.password_validators.ComplexityValidator",
    },
    {
        "NAME": "validator.password_validators.ReusedValidator",
    },
    {
        "NAME": "validator.password_validators.MinimumChangeIntervalValidator",
    },
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,  # Required for Swagger UI to find templates
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",  # Required for Swagger UI
            ],
        },
    }
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'utils.pagination.Pagination',
    # 'PAGE_SIZE': env.str('DJANGO_PAGE_SIZE', 5),
    "DEFAULT_METADATA_CLASS": "rest_framework.metadata.SimpleMetadata",
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
}

DRF_STANDARDIZED_ERRORS = {"ENABLE_IN_DEBUG_FOR_UNHANDLED_EXCEPTIONS": True}

SPECTACULAR_SETTINGS = {
    "TITLE": "Lockey API",
    "DESCRIPTION": "API documentation for Lockey secret management app",
    "VERSION": "v1",
    "CONTACT": {"email": "milad.moslehikhou@gmail.com"},
    "SERVE_INCLUDE_SCHEMA": False,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "()": "utils.logging.ColoredFormatter",
            "format": "%(asctime)s.%(msecs)03d %(levelname)-8s [%(process)d-%(thread)d] [%(name)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "default"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": env.str("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": env.str("DJANGO_LOG_LEVEL", "DEBUG" if DEBUG else "INFO"),
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": env.str("ORM_LOG_LEVEL", "DEBUG" if DEBUG else "INFO"),
            "propagate": False,
        },
        "lockey": {
            "handlers": ["console"],
            "level": env.str("LOCKEY_LOG_LEVEL", "DEBUG" if DEBUG else "INFO"),
            "propagate": False,
        },
        "lockey.security": {
            "handlers": ["console"],
            "level": env.str("LOCKEY_LOG_LEVEL", "DEBUG" if DEBUG else "INFO"),
            "propagate": False,
        },
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
APPEND_SLASH = False

DEFAULT_MAX_DIGIT = 34
DEFAULT_DECIMAL_PLACES = 2
