# Generated by Django 4.2.19 on 2025-02-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_otp_enabled",
            field=models.BooleanField(default=False, verbose_name="is OTP enabled"),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_secret",
            field=models.CharField(blank=True, max_length=32, verbose_name="OTP secret"),
        ),
    ]
