# Generated by Django 4.2.19 on 2025-02-28 15:41

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=32, verbose_name='OTP secret')),
        ),
    ]
