# Generated by Django 4.2.19 on 2025-02-13 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("folder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("username", models.CharField(max_length=150, verbose_name="username")),
                ("ip", models.CharField(blank=True, max_length=15, verbose_name="ip address")),
                ("uri", models.URLField(blank=True, verbose_name="uri")),
                (
                    "importancy",
                    models.CharField(
                        choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                        default="LOW",
                        max_length=150,
                        verbose_name="importancy",
                    ),
                ),
                ("auto_genpass", models.BooleanField(default=False, verbose_name="auto generate")),
                ("tags", models.CharField(blank=True, max_length=255, verbose_name="tags")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("modified_at", models.DateTimeField(auto_now=True, verbose_name="modified at")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credentials",
                        to="folder.folder",
                        verbose_name="folder",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        db_column="modified_by",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="modified_credentials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="modified by",
                    ),
                ),
            ],
            options={
                "permissions": (("add_public_credential", "Can add public credential"),),
            },
        ),
        migrations.CreateModel(
            name="CredentialShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("until", models.DateTimeField(verbose_name="shared until")),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="credential.credential"
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        db_column="shared_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_by_me",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="shared by",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        db_column="shared_with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_with_me",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="shared with",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CredentialSecret",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "password",
                    django_cryptography.fields.encrypt(models.CharField(max_length=150, verbose_name="password")),
                ),
                ("expire_at", models.DateTimeField(verbose_name="expire at")),
                ("category", models.TextField(blank=True, max_length=36, verbose_name="category")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_secrets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="secrets", to="credential.credential"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CredentialGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[("VIEW", "View"), ("MODIFY", "Modify")],
                        default="VIEW",
                        max_length=150,
                        verbose_name="action",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="credential.credential"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="auth.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CredentialFavorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="credential.credential",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="credentialgrant",
            constraint=models.UniqueConstraint(
                fields=("credential", "action", "user"), name="uq__credential__action__user"
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialgrant",
            constraint=models.UniqueConstraint(
                fields=("credential", "action", "group"), name="uq__credential__action__group"
            ),
        ),
        migrations.AddConstraint(
            model_name="credentialfavorite",
            constraint=models.UniqueConstraint(fields=("credential", "user"), name="uq__credential__user"),
        ),
    ]
