# Generated by Django 4.2.19 on 2025-02-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credential", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialGrantRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret", models.CharField(max_length=320, verbose_name="secret")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("DONE", "Done")],
                        default="PENDING",
                        max_length=8,
                        verbose_name="status",
                    ),
                ),
                ("until", models.DateTimeField(null=True, verbose_name="until")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
            ],
        ),
        migrations.AddField(
            model_name="credentialgrant",
            name="until",
            field=models.DateTimeField(null=True, verbose_name="shared until"),
        ),
        migrations.AlterField(
            model_name="credential",
            name="importancy",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="LOW",
                max_length=8,
                verbose_name="importancy",
            ),
        ),
        migrations.DeleteModel(
            name="CredentialShare",
        ),
        migrations.AddField(
            model_name="credentialgrantrequest",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="grant_requests", to="credential.credential"
            ),
        ),
        migrations.AddField(
            model_name="credentialgrantrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grant_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requester",
            ),
        ),
        migrations.AddField(
            model_name="credentialgrantrequest",
            name="respondent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grant_response",
                to=settings.AUTH_USER_MODEL,
                verbose_name="respondent",
            ),
        ),
    ]
